### ISSUE TITLE
[Help] Ported other firmware on mks robin

### ISSUE THREAD

**Issue by userosos** [jmz52/MKS-Robin-Bootloader#1]
Привет! Есть плата в принтере, подключённая и настроенная своей прошивкой. Готов помочь в отладке сторонних прошивок на MKS robin. Встроенная настолько ужасная, что печатает с максимальной скоростью всё время. Могу тестировать без экрана и SD card, т. к. печатаю с octoprint.

**Comment by jmz52** [comment]
Pull request for ''Add support for MKS Robin board" to  MarlinFirmware:bugfix-2.0.x
https://github.com/MarlinFirmware/Marlin/pull/12650

Подробности в статье http://3dtoday.ru/blogs/jmz/marlin-robin-two-nozzle/
