### ISSUE TITLE
Bad try on a 2.3 board

### ISSUE THREAD

**Issue by youprint** [jmz52/MKS-Robin-Bootloader#2]
Hi
i unfortunatly tried to connect the board via my ST link before reading this : 
https://3dtoday.ru/blogs/jmz/mks-robin-part-two-the-taming-of-the-shrew-firmware/
So i have an expensive dev board now, all the chip was erased. So i decided to try your original bootloader without success (i think they are different from 2.3 to 2.4) 
I have full access to the chip and i'm thiking about Marlin 2.0 but i have to do some RE for pins defs. Thanks for your work, unfortunatly for me you did this for a 2.4.

**Comment by jmz52** [comment]
v2.4 bootloader works on v2.3 board just fine (confirmed by v2.3 owner)
You can download it from [here](https://reprap.org/forum/file.php?13,file=108330,filename=MKS_Robin_v2_4_bootloader.bin,download=1)

Marlin 2.0 work on MKS Robin with or without the original bootloader
Read https://github.com/MarlinFirmware/Marlin/issues/9771 for details
Pins are defined in pins_MKS_ROBIN.h, configuration files can be found in config/examples/Mks/Robin

**Comment by jmz52** [comment]
https://github.com/MarlinFirmware/Marlin/issues/9771#issuecomment-464850378
