### ISSUE TITLE
Port to Trigorilla Pro?

### ISSUE THREAD

**Issue by TheNitek** [jmz52/MKS-Robin-Bootloader#4]
I am currently trying to get this ported to the trigorilla pro, so I can update it's firmware using the standard bootloader instead of the USB flashing. The boards seem to be quite similar, so I am hoping the encryption will be as well.  Do you have any hints on where to find the key?
Probably it would even work to flash the Robin bootloader to the trigorilla, but I am hoping to also use this for stock trigorilla boards.

**Comment by jmz52** [comment]
Hi,
Trigorilla Pro is made by different manufacturer, so I would not expect it to use the same encryption.

There is an article how MKS Robin was hacked to make it work with custom firmware, but it is only available in Russian - https://3dtoday.ru/blogs/jmz/mks-robin-part-two-the-taming-of-the-shrew-firmware

Also you may check  Lerdge hacking project logs where hacking process is described in details:
https://hackaday.io/project/162592-lerdge-3d-printer-mainboard-hacking/log/156554-foundational-work
https://hackaday.io/project/162592-lerdge-3d-printer-mainboard-hacking/log/156588-raming-the-rom
https://hackaday.io/project/162592-lerdge-3d-printer-mainboard-hacking/log/156630-sidetracks-setbacks-and-other-issues
https://hackaday.io/project/162592-lerdge-3d-printer-mainboard-hacking/log/156691-finally-results

Also I was told that MKS Robin bootloader works on Trigorilla Pro board, but in this case you can never go back to original firmware.

**Comment by TheNitek** [comment]
Thanks for all the links, that's nice to dig deeper into this topic.

My hope is that the encryption is the same, but only the key is different.
